[package.metadata.deb]
maintainer = "buty4649 <buty4649@gmail.com>"
license-file = ["../LICENSE-APACHE", "3"]
extended-description = """\
Alacritty is the fastest terminal emulator in existence. Using the GPU for \
rendering enables optimizations that simply aren't possible without it.  """
depends = "$auto"
section = "rust"
priority = "optional"
assets = [
    ["../target/release/alacritty", "usr/bin/", "755"],
    ["../extra/linux/Alacritty.desktop", "usr/share/applications/", "644"],
    ["../extra/logo/alacritty-term.svg", "usr/share/pixmaps/Alacritty.svg", "644"],
    ["../extra/completions/alacritty.bash", "usr/share/bash-completion/completions/alacritty", "644"],
    ["../extra/completions/alacritty.fish", "usr/share/fish/completions/alacritty.fish", "644"],
    ["../extra/completions/_alacritty", "usr/share/zsh/vendor-completions/_alacritty", "644"],
]
maintainer-scripts = "../extra/linux/debian"
